// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

import React from "react";
import RootLayout from "../layout";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div>layout.tsx test</div>
//         {children}
//       </body>
//     </html>
//   );
// }

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <div>
      layout.tsx test 2 boi
      {children}

    </div>
    </>

  )
}