// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div>layout.tsx test</div>
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Sin Ho Ko",
  description: "Sin Ho Ko",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* <body className="flex h-dvh flex-col items-center justify-center bg-gradient-to-r from-blue-700">
        <div className="flex max-h-[800px] w-full max-w-screen-xl grow flex-col rounded-lg border-4 border-dashed border-teal-500">
          <Header />
          {children}
        </div>
      </body> */}
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/icon.png" type="image/png" sizes="32x32" />
        <link
          rel="apple-touch-icon"
          href="/apple-touch-icon.png"
          type="image/png"
          sizes="180x180"
        />
      </head>
      <body className="h-dvh overflow-hidden bg-gradient-to-tl from-purple-950 to-red-700">
        {children}
      </body>
    </html>
  )
}
